### ISSUE TITLE
Torus is a square

### ISSUE THREAD

**Issue by NiklasLeukroth** [StarSimVR/godot#4]
The torus logic, which is for example used in the ring of saturn is currently a square, not a torus, see image below.

![grafik](https://user-images.githubusercontent.com/58695951/176884933-1e4788f3-7303-4844-a430-410dad618530.png)

**Comment by kevinmatthes** [comment]
If one of you pushes to the current `bugFix` branch a commit named `Fix #4`, GitHub will automatically close the corresponding issue when the related Pull Request is merged into `master`.

You can also just force-push to the current branch amending the latest commit in order to rename it.  This will work, too.

**Comment by kevinmatthes** [comment]
To me, the solid looks more like a cuboid, does it not?

However, would it work for you to use the mathematical specification of a torus of genus 1 to fix this issue?

**Comment by kevinmatthes** [comment]
Using half-space magic, a torus of genus 1 is specified in an algebraic manner as
$$
(x ^ 2 + y ^ 2 + z ^ 2 - r_2 ^ 2 - r_1 ^ 2) ^ 2 - 4 \cdot r_2 ^ 2 \cdot (r_1 ^ 2 - z ^ 2) \leq 0 \, .
$$

This should look familiar to you, @Ranplax.

Would this be more efficient than the current solution or would the overhead be too much, @Luka-sama?
